version: '3'
services:
  apigateway:
    build:
      context: .
    container_name: KnowledgeBase
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: